branch-defaults:
  master:
    environment: monitoring-artaka
    group _suffix: null
global:
  application_name: monitoring-artaka
  branch: null
  default_ec2_keyname: ihsan-artaka
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ihsan-artaka
  repository: null
  sc: git
  workspace_type: Application
